### PR TITLE
As it took me a moment to understand your implementation of "intersec…

### PR DESCRIPTION
**Pull request by michaelherger**
…tion", I decided to be a smart ass again :-).

- no need to filter the initial codecs list
- create a hash of the member's codecs, to be used in the grep filter expression

This doesn't change anything about the result, but is easier to read in my eyes.

Other than that thanks for having me read List::Util again. I totally forgot about its features.

### CODE REVIEW

**Comment by philippe44** [comment]
Thanks :-) One comment though. The reason why I used a reference on codecs instead of an array is that if intersection becomes empty, then an array on codec is empty as well and then the loop takes the codecs of the next member which makes the intersection result wrong, no?

**Comment by michaelherger** [comment]
Heh... you're right. But then... an empty intersection sounds unlikely. And useless anyway. I would live with that.

**Comment by philippe44** [comment]
It can happen when, for example, some squeezelite-based players have restricted codecs (and with my bridges it can happen) so this ends with a wrong intersection. Not a big deal at the end because the LMS sync engine will sort this out by doing himself an intersection, but I thought this was precisely what you wanted to avoid (have the group player with wrong codecs and let LMS handle it)

**Comment by michaelherger** [comment]
Argh... it's such a pain to be a smart ass... point taken :-).

**Pull request merged**
