### PR TITLE
Override S::P::Client->chunks to not store any chunks for Groups player

### PR DESCRIPTION
**Pull request by michaelherger**
The original is a simple ->chunks() accessor. Let's override it with a sub always returning an empty list ref, not storing whatever it is sent. This would get rid of those large chunks of code you had to copy over from the original Source module, reducing the risk of introducing side-effects.

If that turns out to work as expected, you'd probably be able to get rid of all the chunks buffer clearing code.

### CODE REVIEW

**Comment by philippe44** [comment]
Of course, this is so much smarter - I’m dumb. 
Thanks Michael

**Comment by michaelherger** [comment]
Don't feel dump. I think you've got a better understanding of the streaming code by now than I do! Trying to understand what you're doing tells me a lot about the core code. It's stuff I've rarely ever touched.

**Comment by philippe44** [comment]
Thanks :-) it was very challenging for me but at least now I have a better idea of LMS in general - I don’t know if you saw but I took another fight with code on XMLBrowser ... need a full aspirin box, but there is something there between iPeng and LMS I don’t know and it might be similar to a issue I had in the past where I wanted to have 2 layers of search but LMS did not let me as the crumbs mechanisms did not work when going back through the layers - or my {items} were set wrong

**Comment by philippe44** [comment]
Oh, another thing about players. How can I change their LMS icons programmatically? I would like to change the bridges icons and subscribe to the player connection dispatch to do that. I also wanted to have a different modelname but ickstream prevents me to do that, so I’ll to find a different way to detect what is what

**Comment by michaelherger** [comment]
Player icon: probably better discussed elsewhere. It's not simple...

**Pull request merged**
